# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'SwiftAddressBookExample' do
	pod "SwiftAddressBook", :path => "../"
end

target 'SwiftAddressBookExampleTests' do

end

